apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - 127.0.0.1
      - apiserver.cluster.local
      - 10.103.97.2
      - 192.168.1.191
      extraArgs:
        audit-log-format: json
        audit-log-maxage: "7"
        audit-log-maxbackup: "10"
        audit-log-maxsize: "100"
        audit-log-path: /var/log/kubernetes/audit.log
        audit-policy-file: /etc/kubernetes/audit-policy.yml
        authorization-mode: Node,RBAC
        enable-aggregator-routing: "true"
        etcd-servers: https://192.168.1.191:2379
        feature-gates: TTLAfterFinished=true,EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/kubernetes
        mountPath: /etc/kubernetes
        name: audit
        pathType: DirectoryOrCreate
      - hostPath: /var/log/kubernetes
        mountPath: /var/log/kubernetes
        name: audit-log
        pathType: DirectoryOrCreate
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: apiserver.cluster.local:6443
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0
        experimental-cluster-signing-duration: 876000h
        feature-gates: TTLAfterFinished=true,EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.24.0
    networking:
      dnsDomain: cluster.local
      podSubnet: 100.64.0.0/10
      serviceSubnet: 10.96.0.0/22apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - 127.0.0.1
      - apiserver.cluster.local
      - 10.103.97.2
      - 192.168.1.191
      extraArgs:
        audit-log-format: json
        audit-log-maxage: "7"
        audit-log-maxbackup: "10"
        audit-log-maxsize: "100"
        audit-log-path: /var/log/kubernetes/audit.log
        audit-policy-file: /etc/kubernetes/audit-policy.yml
        authorization-mode: Node,RBAC
        enable-aggregator-routing: "true"
        etcd-servers: https://192.168.1.191:2379
        feature-gates: TTLAfterFinished=true,EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/kubernetes
        mountPath: /etc/kubernetes
        name: audit
        pathType: DirectoryOrCreate
      - hostPath: /var/log/kubernetes
        mountPath: /var/log/kubernetes
        name: audit-log
        pathType: DirectoryOrCreate
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: apiserver.cluster.local:6443
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0
        experimental-cluster-signing-duration: 876000h
        feature-gates: TTLAfterFinished=true,EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.24.0
    networking:
      dnsDomain: cluster.local
      podSubnet: 100.64.0.0/10
      serviceSubnet: 10.96.0.0/22
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0
        feature-gates: TTLAfterFinished=true,EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-14T08:47:47Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "199"
  uid: 1033f4f7-98cf-43ea-916d-0973ad29a9df
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0
        feature-gates: TTLAfterFinished=true,EphemeralContainers=true
      extraVolumes:
      - hostPath: /etc/localtime
        mountPath: /etc/localtime
        name: localtime
        pathType: File
        readOnly: true
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-14T08:47:47Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "199"
  uid: 1033f4f7-98cf-43ea-916d-0973ad29a9df